sudo: required

services:
  - docker

script:
  - sudo docker run -it -v "$PWD:/repository" eidham:testing sh -c "
      cd /repository && mkdir build && cd build &&
      cmake -DCMAKE_CXX_FLAGS=-Werror .. &&
      make &&
      CTEST_OUTPUT_ON_FAILURE=1 make test
    "
